services:
  source:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./mysql_raw:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 40s
    
  destination:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 40s
  replicator:
    image: osalvador/replicadb
    volumes:
      - ./replicadb:/home/replicadb/conf/
    depends_on:
      source:
        condition: service_healthy
      destination:
        condition: service_healthy
    # restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080